<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TEST_ALL_ASHIWANI"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="29.414">
  <properties />
            <testcase name="f" time="29.414" classname="com.the_internet_herokuapp.testcase.File_Upload">
                <failure type="org.sikuli.script.FindFailed"
                  message="can not find P(/Users/ashiwani.ranjan/git/UI_Automation_Framework/src/test/resources/open.PNG) S: 0.7 in S(0)[0,0 1440x900]"
              >
<![CDATA[FindFailed: can not find P(/Users/ashiwani.ranjan/git/UI_Automation_Framework/src/test/resources/open.PNG) S: 0.7 in S(0)[0,0 1440x900]
  Line 2189, in file Region.java

  org.sikuli.script.Region.handleFindFailedShowDialog(Region.java:2189)
  org.sikuli.script.Region.handleFindFailed(Region.java:2134)
  org.sikuli.script.Region.wait(Region.java:2546)
  org.sikuli.script.Region.find(Region.java:2205)
  org.sikuli.script.Region.getLocationFromTarget(Region.java:3067)
  org.sikuli.script.Region.click(Region.java:3534)
  org.sikuli.script.Region.click(Region.java:3519)
  com.the_internet_herokuapp.testcase.File_Upload.f(File_Upload.java:31)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
