<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Listener Practice Suite " duration-ms="45" started-at="2018-05-26T17:51:29Z" finished-at="2018-05-26T17:51:29Z">
    <groups>
    </groups>
    <test name="TEST_ALL_ASHIWANI" duration-ms="45" started-at="2018-05-26T17:51:29Z" finished-at="2018-05-26T17:51:29Z">
      <class name="com.testng.listner.ListenerTest">
        <test-method status="PASS" signature="Test4()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test4" is-config="true" duration-ms="5" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test1" duration-ms="4" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="Test5()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test5" is-config="true" duration-ms="1" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test5 -->
        <test-method status="FAIL" signature="Test2()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test2" duration-ms="4" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [B] but found [A]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [B] but found [A]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.testng.listner.ListenerTest.Test2(ListenerTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="Test4()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test4" is-config="true" duration-ms="0" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method status="PASS" signature="Test5()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test5" is-config="true" duration-ms="0" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test5 -->
        <test-method status="SKIP" signature="Test3()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test3" duration-ms="1" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This is a skip exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This is a skip exception
	at com.testng.listner.ListenerTest.Test3(ListenerTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="Test4()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test4" is-config="true" duration-ms="0" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method status="PASS" signature="Test5()[pri:0, instance:com.testng.listner.ListenerTest@464bee09]" name="Test5" is-config="true" duration-ms="0" started-at="2018-05-26T23:21:29Z" finished-at="2018-05-26T23:21:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test5 -->
      </class> <!-- com.testng.listner.ListenerTest -->
    </test> <!-- TEST_ALL_ASHIWANI -->
  </suite> <!-- Listener Practice Suite  -->
</testng-results>
